
// This file has been generated by the GUI designer. Do not modify.
namespace NitroStreamGtk.View
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action ConfigAction;
		
		private global::Gtk.Action AboutAction;
		
		private global::Gtk.Action openAction;
		
		private global::Gtk.Action CreditsAction;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.MenuBar Menu;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Button btnUpdate;
		
		private global::Gtk.Button button10;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.ComboBox cmbViewmode;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.SpinButton spinQuality;
		
		private global::Gtk.Entry txtBottomScale;
		
		private global::Gtk.Entry txtIP;
		
		private global::Gtk.Entry txtTopScale;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.ComboBox cmbScreen;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Entry txtPriority;
		
		private global::Gtk.Entry txtQoS;
		
		private global::Gtk.Label GtkLabel4;
		
		private global::Gtk.ScrolledWindow logScroller;
		
		private global::Gtk.TextView txtLog;
		
		private global::Gtk.Button button1;
		
		private global::Gtk.Button button2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget NitroStreamGtk.View.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.ConfigAction = new global::Gtk.Action ("ConfigAction", global::Mono.Unix.Catalog.GetString ("Config"), null, null);
			this.ConfigAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Config");
			w1.Add (this.ConfigAction, null);
			this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
			this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.AboutAction, null);
			this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Define NTRViewer path"), null, "gtk-open");
			this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Define NTRViewer path");
			w1.Add (this.openAction, null);
			this.CreditsAction = new global::Gtk.Action ("CreditsAction", global::Mono.Unix.Catalog.GetString ("Credits"), null, null);
			this.CreditsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Credits");
			w1.Add (this.CreditsAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "NitroStreamGtk.View.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Nitro Stream GTK#");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("NitroStreamMono.icon.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Container child NitroStreamGtk.View.MainWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.WidthRequest = 500;
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='Menu'><menu name='ConfigAction' action='ConfigAction'><menuitem name='openAction' action='openAction'/></menu><menu name='AboutAction' action='AboutAction'><menuitem name='CreditsAction' action='CreditsAction'/></menu></menubar></ui>");
			this.Menu = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/Menu")));
			this.Menu.Name = "Menu";
			this.vbox2.Add (this.Menu);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.Menu]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnUpdate = new global::Gtk.Button ();
			this.btnUpdate.TooltipMarkup = "Button will enable if an update is released";
			this.btnUpdate.Sensitive = false;
			this.btnUpdate.CanFocus = true;
			this.btnUpdate.Name = "btnUpdate";
			this.btnUpdate.UseUnderline = true;
			this.btnUpdate.BorderWidth = ((uint)(3));
			this.btnUpdate.Label = global::Mono.Unix.Catalog.GetString ("No updates available.");
			this.hbox4.Add (this.btnUpdate);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnUpdate]));
			w3.Position = 0;
			w3.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button10 = new global::Gtk.Button ();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.button10.BorderWidth = ((uint)(3));
			this.button10.Label = global::Mono.Unix.Catalog.GetString ("Donate");
			this.hbox4.Add (this.button10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button10]));
			w4.Position = 1;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(20));
			this.table2.BorderWidth = ((uint)(15));
			// Container child table2.Gtk.Table+TableChild
			this.cmbViewmode = global::Gtk.ComboBox.NewText ();
			this.cmbViewmode.AppendText (global::Mono.Unix.Catalog.GetString ("Vertical"));
			this.cmbViewmode.AppendText (global::Mono.Unix.Catalog.GetString ("Horizontal"));
			this.cmbViewmode.Name = "cmbViewmode";
			this.table2.Add (this.cmbViewmode);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.cmbViewmode]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("3DS IP address:");
			this.table2.Add (this.label1);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.label1]));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Top Screen Scale:");
			this.table2.Add (this.label2);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.label2]));
			w8.TopAttach = ((uint)(1));
			w8.BottomAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Bottom Screen Scale:");
			this.table2.Add (this.label3);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
			w9.TopAttach = ((uint)(2));
			w9.BottomAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Viewmode:");
			this.table2.Add (this.label4);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.label4]));
			w10.TopAttach = ((uint)(3));
			w10.BottomAttach = ((uint)(4));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Quality:");
			this.table2.Add (this.label5);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
			w11.TopAttach = ((uint)(4));
			w11.BottomAttach = ((uint)(5));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.spinQuality = new global::Gtk.SpinButton (0, 100, 1);
			this.spinQuality.CanFocus = true;
			this.spinQuality.Name = "spinQuality";
			this.spinQuality.Adjustment.PageIncrement = 10;
			this.spinQuality.ClimbRate = 1;
			this.spinQuality.Numeric = true;
			this.table2.Add (this.spinQuality);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.spinQuality]));
			w12.TopAttach = ((uint)(4));
			w12.BottomAttach = ((uint)(5));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.txtBottomScale = new global::Gtk.Entry ();
			this.txtBottomScale.CanFocus = true;
			this.txtBottomScale.Name = "txtBottomScale";
			this.txtBottomScale.IsEditable = true;
			this.txtBottomScale.InvisibleChar = '•';
			this.table2.Add (this.txtBottomScale);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtBottomScale]));
			w13.TopAttach = ((uint)(2));
			w13.BottomAttach = ((uint)(3));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.txtIP = new global::Gtk.Entry ();
			this.txtIP.CanFocus = true;
			this.txtIP.Name = "txtIP";
			this.txtIP.IsEditable = true;
			this.txtIP.InvisibleChar = '•';
			this.table2.Add (this.txtIP);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtIP]));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.txtTopScale = new global::Gtk.Entry ();
			this.txtTopScale.CanFocus = true;
			this.txtTopScale.Name = "txtTopScale";
			this.txtTopScale.IsEditable = true;
			this.txtTopScale.InvisibleChar = '•';
			this.table2.Add (this.txtTopScale);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.txtTopScale]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table2]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			this.frame1.BorderWidth = ((uint)(6));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table3 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(20));
			this.table3.BorderWidth = ((uint)(9));
			// Container child table3.Gtk.Table+TableChild
			this.cmbScreen = global::Gtk.ComboBox.NewText ();
			this.cmbScreen.AppendText (global::Mono.Unix.Catalog.GetString ("Top"));
			this.cmbScreen.AppendText (global::Mono.Unix.Catalog.GetString ("Bottom"));
			this.cmbScreen.Name = "cmbScreen";
			this.table3.Add (this.cmbScreen);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3 [this.cmbScreen]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Priority Factor:");
			this.table3.Add (this.label6);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.label6]));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("QoS Value:");
			this.table3.Add (this.label7);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3 [this.label7]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Priortise Screen:");
			this.table3.Add (this.label8);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.label8]));
			w20.TopAttach = ((uint)(2));
			w20.BottomAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.txtPriority = new global::Gtk.Entry ();
			this.txtPriority.CanFocus = true;
			this.txtPriority.Name = "txtPriority";
			this.txtPriority.IsEditable = true;
			this.txtPriority.InvisibleChar = '•';
			this.table3.Add (this.txtPriority);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3 [this.txtPriority]));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.txtQoS = new global::Gtk.Entry ();
			this.txtQoS.CanFocus = true;
			this.txtQoS.Name = "txtQoS";
			this.txtQoS.IsEditable = true;
			this.txtQoS.InvisibleChar = '•';
			this.table3.Add (this.txtQoS);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3 [this.txtQoS]));
			w22.TopAttach = ((uint)(1));
			w22.BottomAttach = ((uint)(2));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.table3);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b> Advanced </b>");
			this.GtkLabel4.UseMarkup = true;
			this.GtkLabel4.SingleLineMode = true;
			this.frame1.LabelWidget = this.GtkLabel4;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w25.Position = 3;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.logScroller = new global::Gtk.ScrolledWindow ();
			this.logScroller.HeightRequest = 200;
			this.logScroller.Name = "logScroller";
			this.logScroller.ShadowType = ((global::Gtk.ShadowType)(1));
			this.logScroller.BorderWidth = ((uint)(6));
			// Container child logScroller.Gtk.Container+ContainerChild
			this.txtLog = new global::Gtk.TextView ();
			this.txtLog.CanFocus = true;
			this.txtLog.Name = "txtLog";
			this.txtLog.WrapMode = ((global::Gtk.WrapMode)(2));
			this.logScroller.Add (this.txtLog);
			this.vbox2.Add (this.logScroller);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.logScroller]));
			w27.PackType = ((global::Gtk.PackType)(1));
			w27.Position = 4;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Connect");
			this.vbox2.Add (this.button1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button1]));
			w28.PackType = ((global::Gtk.PackType)(1));
			w28.Position = 5;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.BorderWidth = ((uint)(3));
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Send Mem Patch");
			this.vbox2.Add (this.button2);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button2]));
			w29.PackType = ((global::Gtk.PackType)(1));
			w29.Position = 6;
			w29.Expand = false;
			w29.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 972;
			this.DefaultHeight = 1004;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.openAction.Activated += new global::System.EventHandler (this.DefineViewrPath);
			this.btnUpdate.Pressed += new global::System.EventHandler (this.onUpdateButtonPress);
			this.button10.Pressed += new global::System.EventHandler (this.onDonateClick);
			this.button2.Pressed += new global::System.EventHandler (this.onSendMemoryPatch);
			this.button1.Pressed += new global::System.EventHandler (this.onConnectButtonClicked);
		}
	}
}
